# Generated by Django 5.2.15 on 2026-07-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_instructorprofile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='student_id',
            field=models.CharField(db_index=True, editable=False, max_length=8, null=True),
        ),
    ]
