# Generated by Django 5.2.15 on 2026-07-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
    ]
