# Generated by Django 5.2.15 on 2026-07-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_category_image_file_course_is_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image_file',
            field=models.FileField(blank=True, null=True, upload_to='courses/images/'),
        ),
    ]
