# Generated by Django 5.2.15 on 2026-07-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_alter_course_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolledstudent',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
